public VIRTUAL class DortAyaklilar EXTENDS Canlilar {
    /*public void Solunum(){
        system.debug('DortAyaklilar solunum yapar.');
    }
    public void Hareket(){
        system.debug('DortAyaklilar hareket eder.');
    }*/
	
    /*
    //OVERRIDE
    public VIRTUAL String Beslenme(String Besin){
        system.debug('DortAyaklilar ' + Besin+ ' ile beslenir.');
        return besin; 
    }
 */
    public void kil(){
        system.debug('DortAyaklilarin vucudu kil ile kaplidir.');
    }    
}